services:
  mysql:
    container_name: mysql
    image: mysql:9
    restart: always
    secrets:
      - db-password
    environment:
      MYSQL_DATABASE: keycloak
      MYSQL_USER: keycloak
      MYSQL_PASSWORD: keycloak
      MYSQL_ROOT_PASSWORD: /run/secrets/db-password
    networks:
      - app-network
    ports:
      - 3306:3306
    volumes:
      - db-data:/var/lib/mysql
    healthcheck:
      test: mysqladmin ping -h localhost -p$$MYSQL_ROOT_PASSWORD
      interval: 5s
      timeout: 2s
      retries: 10

  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:25.0.2
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KC_DB: mysql
      KC_DB_URL_HOST: mysql
      KC_DB_URL_DATABASE: keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: ${KC_DB_PASSWORD}
      KC_LOG_LEVEL: INFO,org.infinispan:DEBUG,org.keycloak.events:DEBUG
      KC_HEALTH_ENABLED: true
    command: ["start-dev", "--import-realm"]
    ports:
      - 8080:8080
    volumes:
      - ./keycloak-init:/opt/keycloak/data/import:rw
      - keycloak-data:/opt/keycloak/data
    networks:
      - app-network
    depends_on:
      mysql:
        condition: service_healthy

volumes:
  db-data: null
  keycloak-data: null

secrets:
  db-password:
    file: db/password.txt

networks:
  app-network:
    driver: bridge
